version: "3"

services:
  
  wordpress:
    extends:
      file: ./containers/wordpress/wordpress.yaml
      service: wordpress
  
  database:
    extends:
      file: ./containers/mariadb/mariadb.yaml
      service: mariadb
      
  phpmyadmin:
    extends:
      file: ./containers/phpmyadmin/phpmyadmin.yaml
      service: phpmyadmin
  
volumes:
  wp_data:
  db_data: